### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by JanSzidat** [pauloamgomes/Cockpit-CustomComponents#3]
Hi,
I just put all the files in the /addons/CustomComponents folder, but it's not working. I still see all the Layout Components. I added the JSON block with some enabled components.
Are there any other necessary steps to follow for it to work?

Thanks
Jan

**Comment by pauloamgomes** [comment]
Hi @JanSzidat , can you provide a screenshot of the layout field configuration?

**Comment by JanSzidat** [comment]
![1](https://user-images.githubusercontent.com/2026912/53401759-b67a3380-39b0-11e9-88ba-c844aefeb664.jpg)

It's a Layout component called Gallery with a Layout field that should only allow Images and Videos. (Both are Layout Components as well)

**Comment by pauloamgomes** [comment]
And your components are named exactly video and image?

**Comment by JanSzidat** [comment]
Yes. Is there any way to see if the add-on is recognized at all? Should there be a tile under settings?

**Comment by pauloamgomes** [comment]
Ok, just to confirm, please provide a screenshot of your layout components page (in the settings page) and confirm that you don't have any js error when opening the layout popup.

**Comment by JanSzidat** [comment]
I renamed the components. Do I have to enter the name or the label in the JSON part?

![14](https://user-images.githubusercontent.com/2026912/53405754-ceee4c00-39b8-11e9-8cec-4d7156b9e657.jpg)
![11](https://user-images.githubusercontent.com/2026912/53405761-d7468700-39b8-11e9-968f-6def645b786c.jpg)
![12](https://user-images.githubusercontent.com/2026912/53405775-de6d9500-39b8-11e9-8a04-178b2efe42df.jpg)
![13](https://user-images.githubusercontent.com/2026912/53405776-de6d9500-39b8-11e9-8717-e3a342cb8164.jpg)

**Comment by pauloamgomes** [comment]
It should be the component name and not the label, so your configuration looks good. Are you using a recent cockpit next version?

**Comment by JanSzidat** [comment]
Yes, I'm using the latest version.

**Comment by pauloamgomes** [comment]
Not really sure what could be happening, to recap, if you have `cockpit_dir/addons/CustomComponents` so you can see `cockpit_dir/addons/CustomComponents/bootstrap.php` file the module is loaded and will check for the enabled option and remove all other components, I have it working on multiple cockpit instances. Did you confirmed you don't have any JS error on the page?

**Comment by JanSzidat** [comment]
I don't get any JS errors. The components.js gets loaded, too.
I think the problem is that I don't have the field.params.opts at all, although I have the correct JSON in the Layout field.

![55](https://user-images.githubusercontent.com/2026912/53554978-40590680-3b41-11e9-8cdd-e7837ba6abe5.jpg)

**Comment by pauloamgomes** [comment]
That code runs in a trigger action, so it may be possible that the field is not yet fully loaded, so the params.opts would not appear in the console inspector. Increased the setTimeout value, can you confirm if that helped?

**Comment by JanSzidat** [comment]
I just increased the setTimeout to 5000ms and it didn't help.

**Comment by pauloamgomes** [comment]
Ok, that's weird, the field.params.opts should be present.
You can also test the opposite (in that case supported by cockpit core), instead of defining the enabled components you can define the ones you want to exclude, e.g.:

```
{
  "exclude": ["..."]
}

**Comment by JanSzidat** [comment]
Still no success. I only have the field.params.components.

**Comment by pauloamgomes** [comment]
Humm, looking to your first comments, realized that you are doing it in a layout component and not a collection field, right?
If that is the case you may need to define the json in a different structure, e.g:

```json
{
  "opts": {
    "enabled": ["Comp1", "Comp2"]
  }
}
```

**Comment by JanSzidat** [comment]
I tried to use the Layout field on singletons, collection entries and in LayoutComponents. Still no opts.

**Comment by pauloamgomes** [comment]
Sorry, my bad, on the layout components field structure, when you need to pass opts you need to use:

```json
{
  "options": {
    "enabled": ["Comp1", "Comp2"]
  }
}
```

keep in mind that for collections/singleton fields it should work as discussed before.
If that is still not working my suggestion is to create another empty instance of cockpit only with that addon and try there.

**Comment by JanSzidat** [comment]
I have `App.trigger('field.layout.components', {components:this.components});` in my /modules/Cockpit/assets/components.js:2606.
If I change it to `App.trigger('field.layout.components', {components:this.components,opts:opts});`
Everything is working as expected.

**Comment by pauloamgomes** [comment]
Something is wrong with your installation, seems to be outdated, on latests versions of cockpit the trigger is on line 2699 as below::

```
App.trigger('field.layout.components', {components:this.components, opts:opts});
```
