### ISSUE TITLE
Is this addon obsolete? 

### ISSUE THREAD

**Issue by raffaelj** [pauloamgomes/Cockpit-CustomComponents#7]
Since [this commit][1] it is possible to use a `restrict` key in the field options of a layout field. It seems to have the same impact as your addon with the `enabled` key. Even better, there is no empty group tab anymore if I use `restrict` instead of `enabled` with disabled components that aren't in the core group. 

Did I miss something or is this addon now obsolete?

[1]: https://github.com/agentejo/cockpit/commit/d440ae7b5344d5eb24987f2391a84529224528c2

**Comment by pauloamgomes** [comment]
Thanks for flagging @raffaelj , it indeed seems so.
